export const fileList = [
  'src/features/auth/components/LoginForm.tsx',
  'src/features/auth/components/RegisterForm.tsx',
  'src/features/dashboard/components/DashboardLayout.tsx',
  'src/features/dashboard/components/Sidebar.tsx',
  'src/features/dashboard/components/Header.tsx',
  'src/features/projects/components/ProjectCard.tsx',
  'src/features/projects/components/ProjectList.tsx',
  'src/features/projects/hooks/useProjects.ts',
  'src/features/settings/components/SettingsForm.tsx',
  'src/features/settings/components/ThemeSelector.tsx',
  'src/shared/components/Button.tsx',
  'src/shared/components/Input.tsx',
  'src/shared/hooks/useAuth.ts',
  'src/shared/utils/api.ts',
  'src/shared/utils/validation.ts',
  'public/index.html',
  'public/favicon.ico'
];